# -*- coding: utf-8 -*-
"""
Скрипт для формирования данных для векторной БД (Pinecone, Qdrant, ChromaDB).
"""

import json
import uuid
from pathlib import Path
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, asdict

from parser import ClinicalProtocolParser, ClinicalChunk


@dataclass
class VectorRecord:
    """Запись для векторной БД."""
    id: str
    vector: List[float]  # Will be generated by embedding model
    text: str
    metadata: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "vector": self.vector,
            "text": self.text,
            "metadata": self.metadata
        }


class VectorDBExporter:
    """Экспортёр данных для векторных БД."""

    def __init__(self):
        self.parser = ClinicalProtocolParser()

    def create_chunks_for_embedding(self, chunks: List[ClinicalChunk]) -> List[VectorRecord]:
        """Создание записей для векторизации."""
        records = []

        for chunk in chunks:
            # Основной текст для векторизации
            text = self._build_searchable_text(chunk)

            record = VectorRecord(
                id=chunk.chunk_id,
                vector=[],  # Will be filled by embedding model
                text=text,
                metadata={
                    "diagnosis": chunk.diagnosis,
                    "icd_code": chunk.icd_code,
                    "section_type": chunk.section_type,
                    "title": chunk.title,
                    "medications": [m.get("name", "") for m in chunk.medications],
                    "contraindications": chunk.contraindications,
                    "source_file": chunk.source_file,
                    "source_page": chunk.source_page
                }
            )
            records.append(record)

        return records

    def _build_searchable_text(self, chunk: ClinicalChunk) -> str:
        """Построение текста для поиска."""
        parts = []

        # Заголовок
        parts.append(f"Диагноз: {chunk.diagnosis} ({chunk.icd_code})")
        parts.append(f"Раздел: {chunk.section_type}")

        # Основной контент
        parts.append(chunk.content)

        # Препараты
        if chunk.medications:
            med_names = [m.get("name", "") for m in chunk.medications]
            parts.append(f"Препараты: {', '.join(med_names)}")

            for med in chunk.medications:
                med_text = f"{med.get('name', '')}"
                if med.get('dosage'):
                    med_text += f" {med.get('dosage')}"
                if med.get('route'):
                    med_text += f" {med.get('route')}"
                parts.append(med_text)

        # Противопоказания
        if chunk.contraindications:
            parts.append(f"Противопоказания: {', '.join(chunk.contraindications)}")

        # Процедуры
        if chunk.procedures:
            parts.append(f"Процедуры: {', '.join(chunk.procedures)}")

        return "\n".join(parts)

    def export_for_pinecone(self, chunks: List[ClinicalChunk], output_path: str):
        """Экспорт в формате Pinecone."""
        records = self.create_chunks_for_embedding(chunks)

        # Pinecone expects: id, values (vector), metadata
        pinecone_data = []
        for record in records:
            pinecone_data.append({
                "id": record.id,
                "values": record.vector,  # Placeholder
                "metadata": record.metadata
            })

        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(pinecone_data, f, ensure_ascii=False, indent=2)

        print(f"Pinecone формат сохранён: {output_path}")

    def export_for_qdrant(self, chunks: List[ClinicalChunk], output_path: str):
        """Экспорт в формате Qdrant."""
        records = self.create_chunks_for_embedding(chunks)

        # Qdrant point structure
        qdrant_data = []
        for record in records:
            qdrant_data.append({
                "id": record.id,
                "vector": record.vector,  # Placeholder
                "payload": record.metadata
            })

        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(qdrant_data, f, ensure_ascii=False, indent=2)

        print(f"Qdrant формат сохранён: {output_path}")

    def export_for_chromadb(self, chunks: List[ClinicalChunk], output_path: str):
        """Экспорт в формате ChromaDB."""
        records = self.create_chunks_for_embedding(chunks)

        chroma_data = {
            "ids": [r.id for r in records],
            "embeddings": [r.vector for r in records],  # Placeholder
            "metadatas": [r.metadata for r in records],
            "documents": [self._build_searchable_text(c) for c in chunks]
        }

        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(chroma_data, f, ensure_ascii=False, indent=2)

        print(f"ChromaDB формат сохранён: {output_path}")

    def generate_sample_with_openai(self, chunks: List[ClinicalChunk], api_key: str, output_path: str):
        """Генерация эмбеддингов через OpenAI."""
        try:
            import openai
        except ImportError:
            print("Установите openai: pip install openai")
            return

        openai.api_key = api_key
        records = self.create_chunks_for_embedding(chunks)

        batch_size = 100
        for i in range(0, len(records), batch_size):
            batch = records[i:i+batch_size]
            texts = [self._build_searchable_text(chunks[j]) for j in range(i, min(i+batch_size, len(chunks)))]

            response = openai.Embedding.create(
                model="text-embedding-ada-002",
                input=texts
            )

            for j, embedding in enumerate(response['data']):
                chunk_idx = i + j
                chunks[chunk_idx].chunk_id  # Already set

        # Сохранение с эмбеддингами
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump([c.to_dict() for c in chunks], f, ensure_ascii=False, indent=2)

        print(f"Данные с эмбеддингами сохранены: {output_path}")


def main():
    """CLI интерфейс."""
    import argparse

    parser = argparse.ArgumentParser(description='Экспорт для векторных БД')
    parser.add_argument('input', help='Путь к файлу, директории или JSON с chunks')
    parser.add_argument('-o', '--output', required=True, help='Путь для сохранения')
    parser.add_argument('--format', choices=['pinecone', 'qdrant', 'chromadb', 'openai'],
                       default='pinecone', help='Формат векторной БД')
    parser.add_argument('--api-key', help='API ключ OpenAI (для --format openai)')
    parser.add_argument('--recursive', action='store_true', help='Рекурсивный обход')

    args = parser.parse_args()

    exporter = VectorDBExporter()

    # Загрузка или парсинг
    if args.input.endswith('.json'):
        with open(args.input, 'r', encoding='utf-8') as f:
            chunks_data = json.load(f)
        # Конвертация обратно в ClinicalChunk
        from extractors import ClinicalChunk
        chunks = [ClinicalChunk(**cd) for cd in chunks_data]
    else:
        parser_inst = ClinicalProtocolParser()
        path = Path(args.input)
        if path.is_dir():
            chunks = parser_inst.parse_directory(args.input, args.recursive)
        else:
            chunks = parser_inst.parse_file(args.input)

    print(f"Обработано фрагментов: {len(chunks)}")

    # Экспорт
    if args.format == 'pinecone':
        exporter.export_for_pinecone(chunks, args.output)
    elif args.format == 'qdrant':
        exporter.export_for_qdrant(chunks, args.output)
    elif args.format == 'chromadb':
        exporter.export_for_chromadb(chunks, args.output)
    elif args.format == 'openai':
        if not args.api_key:
            print("Ошибка: требуется --api-key для OpenAI")
            return
        exporter.generate_sample_with_openai(chunks, args.api_key, args.output)


if __name__ == '__main__':
    main()
